version: '3' #  Docker Compose 파일의 버전을 지정
services: # 서비스 섹션의 시작을 나타냄. 이 섹션에서는 컨테이너화할 서비스를 정의
  mysql:
    image: mysql:8.0.33 # 2023. 04. 30 기준으로 가장 최신버전 :: MySQL 서비스가 사용할 도커 이미지를 지정
    container_name: cat-picture-db # MySQL 컨테이너의 이름을 "cat-picture-db"로 지정, 컨테이너의 고유 식별자
    ports:
      - 3306:3306 # HOST:CONTAINER ; 포트 매핑을 설정 ,  호스트의 3306 포트와 컨테이너의 3306 포트를 매핑하여 외부에서 MySQL 서버에 접근할 수 있게 함
    environment: # 환경 변수를 설정
      MYSQL_ROOT_PASSWORD: admin # MySQL root 사용자의 비밀번호를 "admin"으로 설정
      # MYSQL_USER: admin # MySQL ROOT 사용자의 이름을 "admin"으로 설정
      # 기본적으로 MySQL 컨테이너는 ROOT 사용자만을 갖고 있으며, 다른 사용자는 생성되지 않는다.
    command: # MySQL 컨테이너가 시작될 때 실행할 명령어를 지정
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes: # 볼륨 매핑을 설정
      - /mysql/data:/var/lib/mysql #  호스트의 /mysql/data 디렉토리를 컨테이너의 /var/lib/mysql 디렉토리에 연결하여 MySQL 데이터를 영속적으로 저장